# Generated by Django 4.0.4 on 2022-05-29 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_collegemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True, null=True)),
                ('entrance', models.TextField(blank=True, null=True)),
                ('fees', models.TextField(blank=True, null=True)),
                ('colleges', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterModelOptions(
            name='collegemodel',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
