# Generated by Django 4.0.4 on 2022-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_coursemodel_alter_collegemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegemodel',
            name='info',
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='admission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='placement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='ranking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
