# Generated by Django 4.0.4 on 2022-06-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_collegemodel_info_collegemodel_admission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegemodel',
            old_name='clg_name',
            new_name='name',
        ),
    ]
