# Generated by Django 4.0.4 on 2022-06-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_collegemodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=8.5, max_digits=2),
            preserve_default=False,
        ),
    ]
