# Generated by Django 4.0.4 on 2022-06-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_collegemodel_photo_collegemodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='college', to='cms.collegemodel'),
            preserve_default=False,
        ),
    ]
