# Generated by Django 4.0.5 on 2022-06-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_collegemodel_photo_collegemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegemodel',
            name='information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
