# Generated by Django 4.0.4 on 2022-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_coursemodel_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='college',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='college',
            field=models.ManyToManyField(related_name='college', to='cms.collegemodel'),
        ),
    ]
