# Generated by Django 4.0.4 on 2022-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_coursemodel_college_coursemodel_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='college',
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='course',
            field=models.ManyToManyField(related_name='course', to='cms.coursemodel'),
        ),
    ]
