# Generated by Django 4.0.4 on 2022-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_collegemodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegemodel',
            name='course',
            field=models.ManyToManyField(related_name='course', to='cms.coursemodel'),
        ),
    ]
