# Generated by Django 4.0.4 on 2022-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_collegemodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='fees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
