# Generated by Django 4.0.4 on 2022-06-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_collegemodel_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='courses_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
