# Generated by Django 4.0.4 on 2022-06-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_collegemodel_information'),
        ('cms', '0015_collegemodel_courses_table'),
    ]

    operations = [
    ]
