# Generated by Django 4.0.4 on 2022-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_merge_20220613_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegemodel',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
