# Generated by Django 4.0.4 on 2022-06-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_collegemodel_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleges', models.ManyToManyField(related_name='navbar', to='cms.collegemodel')),
            ],
        ),
    ]
