# Generated by Django 4.0.4 on 2022-06-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_navbar_remove_collegemodel_course_delete_navbarmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='col_slug',
            field=models.CharField(max_length=300),
        ),
    ]
