# Generated by Django 4.0.4 on 2022-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_navbar_col_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='college',
            new_name='page_type',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='col_slug',
        ),
        migrations.AddField(
            model_name='navbar',
            name='element',
            field=models.TextField(blank=True, null=True),
        ),
    ]
