# Generated by Django 4.0.4 on 2022-06-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_rename_college_navbar_page_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='col',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.collegemodel'),
            preserve_default=False,
        ),
    ]
