# Generated by Django 4.0.4 on 2022-06-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_navbar_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='element',
        ),
    ]
