# Generated by Django 4.0.4 on 2022-06-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_remove_navbar_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='cr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.coursemodel'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='col',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.collegemodel'),
        ),
    ]
