# Generated by Django 4.0.4 on 2022-06-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_alter_navbar_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='fees_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='cr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.coursemodel'),
        ),
    ]
