# Generated by Django 4.0.4 on 2022-06-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_coursemodel_fees_table_alter_navbar_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='admission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
