# Generated by Django 4.0.4 on 2022-06-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_coursemodel_eligibilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
